return {
    ["interface"] = "interface",
    block_construct = "block_construct",
    derived_type_definition = "derived_type_definition",
    derived_type_procedures = "derived_type_procedures",
    do_loop_statement = "do_loop_statement",
    else_clause = "else_clause",
    elseif_clause = "elseif_clause",
    ["function"] = "function",
    function_statement = "function_statement",
    if_statement = "if_statement",
    included_items = "included_items",
    ["subroutine"] = "subroutine",
    assignment_statement = "assignment_statement",
    subroutine_call = "subroutine_call",
    subroutine_statement = "subroutine_statement",
    variable_declaration = "variable_declaration",
}
